apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-example-foo
  namespace: openshift-gitops
spec:
  destination:
    namespace: nginx-example-foo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/eriknelson/nginx-example-foo.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
